### ISSUE TITLE
Installation stuck at " Sync the upstream repo(s) "

### ISSUE THREAD

**Issue by mmuppidi** [UTSA-OCI/OCI-OpenStack-Ansible#1]
Installation is stuck at " Sync the upstream repo(s) " task for more than half an hour while running setup_infrastructure.yml playbook. 

@elextro  any idea how to overcome this.

**Comment by mmuppidi** [comment]
I looks like some kind of problem with rsync -avzlHAX being implemented in repo-clone-mirror.yml. Runs smoothly when options are removed, that is rsync instead of rsync -avzlHAX.

**Comment by alextricity25** [comment]
I haven't seen a bug pop up about this on the upstream repo. I know that there were some recent changes to the way repositories are handled, but those changes have not been back-ported to the kilo branch yet. Could you run the playbook with the "-vvvvv" option and paste the output here?

**Comment by mmuppidi** [comment]
It looks like on the upstream repo the problem has been fixed and this has been tested, everything works fine now. Closing the issue
